const { cmd, commands } = require('../command');

cmd({
    pattern: "Menu1",
    react: "⚡",
    category: "main",
    filename: __filename
}, async (conn, mek, m, { from, pushName, reply }) => {
    try {
        let msg = `*Hello ${pushName}* 👋\n\n`;
        msg += `🤖 *Bot:* MARCEUSE-XMD❤️-2\n`;
        msg += `👑 *Owner:* Nicolaus Daniel ❤️😈😈\n`;
        msg += `📞 *Contact:* +255758575032\n\n`;
        
        msg += `┏━━━━━━━「 COMMANDS 」━━━━━━━┓\n┃ 1. 🚀 *SILA*\n┃ 2. 🚀 *TEST*\n┃ 3. 🚀 *MENU*\n┃ 4. 🚀 *AI*\n┃ 5. 🚀 *HI*\n┃ 6. 🚀 *BOY*\n┃ 7. 🚀 *MARCEUSE-XMD❤️-2*\n┗━━━━━━━━━━━━━━━━━━━━━━━━━━┛\n\n`;
        
        msg += `*📢 NEWSLETTER:*\n *120363407262029751@newsletter*\n\n`;
        msg += `© Generated by Nicolas Daniel 😈V4`;

        await conn.sendMessage(from, { 
            text: msg,
            contextInfo: {
                externalAdReply: {
                    title: "MARCEUSE-XMD❤️-2 SYSTEM",
                    body: "Tap to Join our Channel",
                    thumbnailUrl: " https://files.catbox.moe/8s7lxh.jpg",
                    sourceUrl: "https://whatsapp.com/channel/0029Vb6huZG30LKMFhAjNB3A",
                    mediaType: 1,
                    renderLargerThumbnail: true
                }
            }
        }, { quoted: mek });

    } catch (e) {
        console.log(e);
        reply("❌ Error: " + e.message);
    }
});
