
const { cmd } = require('../command');

cmd({
    pattern: "ping4",
    desc: 'hapa ndipo utaona speed ya bot',
    category: "generated",
    react: "✨",
    filename: __filename
}, async (conn, mek, m, { from, pushName }) => {
    try {
        const date = new Date().toLocaleDateString();
        const time = new Date().toLocaleTimeString();
        const styles = [
            // STYLE 1: BOX STYLE
            `╔════════════════════════╗\n      ⚡ *MARCEUSE-XMD-2❤️* ⚡\n╚════════════════════════╝\n👤 *User:* ${pushName}\n📅 *Date:* ${date}\n⌚ *Time:* ${time}\n👑 *Owner:* MARCEUSE-XMD-2❤️\n\n*📍 Task:* hapa ndipo utaona speed ya bot\n\n> *Powered by Nicolaus Daniel😋 Engine*`,
            
            // STYLE 2: CLEAN LINE STYLE
            `✨ *MARC-XR DYNAMIC MENU* ✨\n\n*━━━━━━━━━━━━━━━━━━━━*\n👤 *Hello:* ${pushName}\n🕒 *Time:* ${time}\n📂 *Command:* ping4\n📝 *Info:* hapa ndipo utaona speed ya bot\n*━━━━━━━━━━━━━━━━━━━━*\n\n> *Generated by MARC-XR System*`,
            
            // STYLE 3: SPARKLE STYLE
            `🌟 ━━━ • ⚡ • ━━━ 🌟\n  *Nicolaus Daniel😋 XMD ENGINE*\n🌟 ━━━ • ⚡ • ━━━ 🌟\n\n👤 *User:* ${pushName}\n📅 *Date:* ${date}\n🚀 *Action:* hapa ndipo utaona speed ya bot\n\n💎 *Enjoy the service!*\n\n> *MARCEUSE-XMD-2❤️ System* `
        ];

        // Hapa bot inachagua urembo mmoja kati ya hiyo mitatu kila inapopigwa command
        const randomStyle = styles[Math.floor(Math.random() * styles.length)];

        await conn.sendMessage(from, { 
            text: randomStyle,
            contextInfo: {
                externalAdReply: {
                    title: "MARCEUSE-XMD-2❤️ 𝙳𝚈𝙽𝙰𝙼𝙸𝙲",
                    body: "Dynamic Fancy Menu",
                    thumbnailUrl: "https://telegra.ph/file/dcce2a3952975107ee010.jpg",
                    sourceUrl: "https://whatsapp.com/channel/0029Vb6huZG30LKMFhAjNB3A",
                    mediaType: 1,
                    renderLargerThumbnail: true
                }
            }
        }, { quoted: mek });
    } catch (e) {
        console.error(e);
    }
});
